version: '3.8'
services:
  next-js:
    build:
      context: . #if Dockerfile is not at the same level change the path here
      target: dev
    restart: always
    command: sh -c "npx prisma db push && yarn next dev"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '${APP_PORT}:3000'
      - 5555:5555
  #    depends_on:
  #      - db

  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
